export const GET_ALBUMS_PROGRESS = 'GET_ALBUMS_PROGRESS';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const RESET_ALBUMS = 'RESET_ALBUMS';
export const CREATE_NEW_ALBUM = 'CREATE_NEW_ALBUM';