export const GET_SEARCH_RESULTS_PROGRESS = 'GET_SEARCH_RESULTS_PROGRESS';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_FAIL = 'GET_SEARCH_RESULTS_FAIL';
export const RESET_VIDEOS = 'RESET_VIDEOS';