export const GET_GROUPS_PROGRESS = 'GET_GROUPS_PROGRESS';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';
export const RESET_GROUPS = 'RESET_PEOPLE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY_ADVANCED_PARAMS = 'RESET_SEARCH_QUERY_ADVANCED_PARAMS';