export const GET_DISCUSSION_PROGRESS = 'GET_DISCUSSIONS_PROGRESS';
export const GET_DISCUSSION_SUCCESS = 'GET_DISCUSSIONS_SUCCESS';
export const GET_DISCUSSION_FAIL = 'GET_DISCUSSIONS_FAIL';
export const RESET_DISCUSSION = 'RESET_DISCUSSIONS';
export const HIDE_DISCUSSION = 'HIDE_DISCUSSION';
export const LOCK_DISCUSSION = 'LOCK_DISCUSSION';
export const DELETE_DISCUSSION = 'DELETE_DISCUSSION';