export const GET_PEOPLE_PROGRESS = 'GET_PEOPLE_PROGRESS';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL';
export const RESET_PEOPLE = 'RESET_PEOPLE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY_ADVANCED_PARAMS = 'RESET_SEARCH_QUERY_ADVANCED_PARAMS';