export const GET_INFOLIST_PROGRESS = 'GET_INFOLIST_PROGRESS';
export const GET_INFOLIST_SUCCESS = 'GET_INFOLIST_SUCCESS';
export const GET_INFOLIST_FAIL = 'GET_INFOLIST_FAIL';
export const RESET_INFOLIST = 'RESET_INFOLIST';
export const ADD_INFO_TO_LIST = 'ADD_INFO_TO_LIST';