export const GET_UPLOADED_VIDEO_PROGRESS = 'GET_UPLOADED_VIDEO_PROGRESS';
export const GET_UPLOADED_VIDEO_SUCCESS = 'GET_UPLOADED_VIDEO_SUCCESS';
export const GET_UPLOADED_VIDEO_FAIL = 'GET_UPLOADED_VIDEO_FAIL';
export const GET_FAVORITE_VIDEO_PROGRESS = 'GET_FAVORITE_VIDEO_PROGRESS';
export const GET_FAVORITE_VIDEO_SUCCESS = 'GET_FAVORITE_VIDEO_SUCCESS';
export const GET_FAVORITE_VIDEO_FAIL = 'GET_FAVORITE_VIDEO_FAIL';
export const RESET_VIDEOS = 'RESET_VIDEOS';