export const GET_DISCUSSIONS_LIST_PROGRESS = 'GET_DISCUSSIONS_LIST_PROGRESS';
export const GET_DISCUSSIONS_LIST_SUCCESS = 'GET_DISCUSSIONS_LIST_SUCCESS';
export const GET_DISCUSSIONS_LIST_FAIL = 'GET_DISCUSSIONS_LIST_FAIL';
export const RESET_DISCUSSIONS_LIST = 'RESET_DISCUSSIONS_LIST';
export const ADD_DISCUSSION = 'ADD_DISCUSSION';