export const GET_AUDIO_PROGRESS = 'GET_AUDIO_PROGRESS';
export const GET_AUDIO_SUCCESS = 'GET_AUDIO_SUCCESS';
export const GET_AUDIO_FAIL = 'GET_AUDIO_FAIL';
export const RESET_AUDIO = 'RESET_AUDIO';
export const ADD_AUDIO = 'ADD_AUDIO';
export const DELETE_AUDIO = 'DELETE_AUDIO';
export const SET_FAVORITE_AUDIO = 'SET_FAVORITE_AUDIO';
export const UNSET_FAVORITE_AUDIO = 'UNSET_FAVORITE_AUDIO';