export const GET_MEMBERS_PROGRESS = 'GET_MEMBERS_PROGRESS';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL';
export const RESET_MEMBERS = 'RESET_MEMBERS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY_ADVANCED_PARAMS = 'RESET_SEARCH_QUERY_ADVANCED_PARAMS';