export const GET_GROUP_ALBUMS_PROGRESS = 'GET_GROUP_ALBUMS_PROGRESS';
export const GET_GROUP_ALBUMS_SUCCESS = 'GET_GROUP_ALBUMS_SUCCESS';
export const GET_GROUP_ALBUMS_FAIL = 'GET_GROUP_ALBUMS_FAIL';
export const RESET_GROUP_ALBUMS = 'RESET_GROUP_ALBUMS';
export const CREATE_NEW_GROUP_ALBUM = 'CREATE_NEW_GROUP_ALBUM';