export const GET_VIDEO_PROGRESS = 'GET_VIDEO_PROGRESS';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAIL = 'GET_VIDEO_FAIL';
export const RESET_VIDEOS = 'RESET_VIDEO';
export const ADD_VIDEO = 'ADD_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';