export const GET_EVENTS_PROGRESS = 'GET_EVENTS_PROGRESS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';
export const RESET_EVENTS = 'RESET_EVENTS';