export const GET_CURRENT_INFO_PROGRESS = 'GET_CURRENT_INFO_PROGRESS';
export const GET_CURRENT_INFO_SUCCESS = 'GET_CURRENT_INFO_SUCCESS';
export const GET_CURRENT_INFO_FAIL = 'GET_CURRENT_INFO_FAIL';
export const RESET_CURRENT_INFO = 'RESET_CURRENT_INFO';
export const UPDATE_CURRENT_INFO = 'UPDATE_CURRENT_INFO';