export const SET_BLACKLIST_PROGRESS = 'SET_BLACKLIST_PROGRESS';
export const SET_BLACKLIST_SUCCESS = 'SET_BLACKLIST_SUCCESS';
export const SET_BLACKLIST_FAIL = 'SET_BLACKLIST_FAIL';
export const RESET_BLACKLIST = 'RESET_BLACKLIST';
export const ADD_TO_BLACKLIST_SUCCESS = 'ADD_TO_BLACKLIST_SUCCESS';
export const ADD_TO_BLACKLIST_FAIL = 'ADD_TO_BLACKLIST_FAIL';
export const REMOVE_FROM_BLACKLIST = 'REMOVE_FROM_BLACKLIST';